changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: New components
      labels:
        - area/components
        - component-proposal
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
        - area/docs
    - title: Maintenance
      labels:
        - "*"
